<center> <h1> DS 3000 </h1> </center>
<center> <h1> Homework Assignment 7 </h1> </center>

<center> <h3> insert your full name here by double-clicking </h3></center>

### What to do

* Carefully read the description.
* Make sure you execute your code for each question and compare the output to the sample output provided.
* Refrain from using advanced Python capabilities that were not covered in class.
* When in doubt, ASK! Post a question on the Blackboard discussion forum for this homework assignment.
* Complete the assignment on your own.

### What to submit
* When you are done with the assignment, save it.
* Download it as a Jupyter Notebook (DS3000_HW7.ipynb)
* Upload your downloaded Notebook to Google Colab (https://colab.research.google.com/notebooks/)
* Get a shareable link to your Notebook on Colab
    * Go to Share near the top-right corner of the screen.
    * Make sure you select Anyone with the Link Can View)
    * Copy the link
* Go to Blackboard
* **Upload your Jupyter Notebook through the Blackboard assignment dropbox link.**
* **Paste the link to you Colab Notebook in the Add Comments field.**
* You can submit multiple attempts. The last attempt will be graded.

<center> <h2> Part 1 </h2> </center>

In this assignment, you will work with one of the popular ML datasets bundled with sci-kit learn: Breast Cancer Wisconsin. You will apply various classifiers to the dataset.

In this part of the assignment, you will retrieve and prepare the dataset for classification.

### Question 1 (2pts)
Write a function that retrieves the Breast Cancer Wisconsin dataset from Sci-kit Learn's datasets module:
    * https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html
    
Your function should return a dataframe containing the features (n = 30) and target variables from this dataset as shown below:
    * Your dataframe should include 569 rows and 31 columns.

Hint: Use the dataset's DESCR attribute to learn more about the dataset and its features.

In [2]:
import pandas as pd

def cancer_dataset():

In [3]:
df = cancer_dataset()
df

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

### Question 2 (4pts)
Write a function that returns the number of benign and malignant cases in the dataset. The target value is 0 for benign cases, while malignant cases have a target value of 1. Your function should take this into account and return labels (benign or malignant) instead of 0 or 1. Refer to the sample output below.

In [4]:
def case_distribution():

In [5]:
case_distribution()

malignant    357
benign       212
Name: target, dtype: int64

### Question 3 (2pts)
Write a function that extracts and returns a tuple of features and target variables from the df dataframe above. Features are all columns from 0 to 29, and the target is the target column.
    * The features variable should be a DataFrame object with 569 rows and 30 columns
    * The target variable should be Series object with 560 values

In [6]:
def features_and_target(df):

In [7]:
features, target = features_and_target(df)

In [8]:
features

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [9]:
target

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int32

<center><h1> Part 2 </h1></center>

In this part, you will apply and evaluate four classifiers (kNN, SVM, Naive Bayes, and Decision Tree) to the breast cancer dataset. You will do so using both of the training/testing approaches we have covered.

### Question 4 (2pts)
You will find it useful to define a dictionary containing these four classifiers so you can apply them in an iteration statement. For this question, import the relevant methods from sci-kit learn.

In [22]:
def estimators.values():
    
#answer goes here

In [24]:
estimators.values()

dict_values([KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform'), SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False), GaussianNB(priors=None, var_smoothing=1e-09), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')])

### Question 5 (8pts)

Write a function that fits these four classifiers using a percentage-split approach. You will first need to split the dataset into training and testing sets. You should use an iteration statement to apply these classifiers. Use random_state=3000 when splitting your dataset.

In [54]:
def classifiers_percentage_split():

In [55]:
classifiers_percentage_split()

k-Nearest Neighbor:
	Prediction accuracy on the test data: 94.41%

Support Vector Machine:
	Prediction accuracy on the test data: 92.31%

Gaussian Naive Bayes:
	Prediction accuracy on the test data: 95.80%

Decision Tree:
	Prediction accuracy on the test data: 93.71%

### Question 6 (8pts)

Write a function that fits these four classifiers using a cross-validation approach. You should use an iteration statement to apply these classifiers. Use random_state=3000 when splitting your dataset.

In [56]:
def classifiers_cross_validation():

In [49]:
classifier_cross_validation()

k-Nearest Neighbor:
	mean accuracy=93.50%, standard deviation=3.77%

Support Vector Machine:
	mean accuracy=91.75%, standard deviation=3.59%

Gaussian Naive Bayes:
	mean accuracy=93.85%, standard deviation=3.25%

Decision Tree:
	mean accuracy=93.33%, standard deviation=2.57%

### Question 7 (4pts)

Based on the results from the previous two questions, what **classifier** and **training/testing** approach would you choose? Why?

Type your answer below: